language: python
python:
  - "3.5"
services:
  - mongodb
  - redis-server
install:
  - "pip install --editable ."
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script: make test-prod
